language: python

addons:
  firefox: "latest"

services:
  - postgresql

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev

install: 
  - pip3 install -r Dependencies/requirements.txt

before_script:
  - psql -c "create database django_acmgeneral;" -U postgres
  - psql -c "CREATE USER djangouser WITH PASSWORD 'djangoUserPassword';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE django_acmgeneral TO djangouser;" -U postgres
  - psql -c "ALTER USER djangouser CREATEDB;" -U postgres
  - cp Dependencies/settings_local.template ACM_General/ACM_General/settings_local.py
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - cd ACM_General
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python3 manage.py test
